name: CI to check simulations

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run simulations, plot generations and video
      run: .github/scripts/run.sh
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fetch tags
        run: git fetch --tags -f
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Upload compiler service to Docker Hub
        run: .github/scripts/docker-release.sh
